/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnimalsRouteImport } from './routes/animals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimalsSlugRouteImport } from './routes/animals.$slug'

const AnimalsRoute = AnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsSlugRoute = AnimalsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AnimalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRouteWithChildren
  '/animals/$slug': typeof AnimalsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRouteWithChildren
  '/animals/$slug': typeof AnimalsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRouteWithChildren
  '/animals/$slug': typeof AnimalsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/animals' | '/animals/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animals' | '/animals/$slug'
  id: '__root__' | '/' | '/animals' | '/animals/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimalsRoute: typeof AnimalsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/animals': {
      id: '/animals'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AnimalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$slug': {
      id: '/animals/$slug'
      path: '/$slug'
      fullPath: '/animals/$slug'
      preLoaderRoute: typeof AnimalsSlugRouteImport
      parentRoute: typeof AnimalsRoute
    }
  }
}

interface AnimalsRouteChildren {
  AnimalsSlugRoute: typeof AnimalsSlugRoute
}

const AnimalsRouteChildren: AnimalsRouteChildren = {
  AnimalsSlugRoute: AnimalsSlugRoute,
}

const AnimalsRouteWithChildren =
  AnimalsRoute._addFileChildren(AnimalsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimalsRoute: AnimalsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
