/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MapRouteImport } from './routes/map'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ConservationRouteImport } from './routes/conservation'
import { Route as AnimalsRouteImport } from './routes/animals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as MissionsSlugRouteImport } from './routes/missions.$slug'
import { Route as AnimalsSlugRouteImport } from './routes/animals.$slug'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ConservationRoute = ConservationRouteImport.update({
  id: '/conservation',
  path: '/conservation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsRoute = AnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsSlugRoute = MissionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MissionsRoute,
} as any)
const AnimalsSlugRoute = AnimalsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AnimalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRouteWithChildren
  '/conservation': typeof ConservationRoute
  '/guide': typeof GuideRoute
  '/kids': typeof KidsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/missions': typeof MissionsRouteWithChildren
  '/passport': typeof PassportRoute
  '/plan': typeof PlanRoute
  '/schedule': typeof ScheduleRoute
  '/animals/$slug': typeof AnimalsSlugRoute
  '/missions/$slug': typeof MissionsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRouteWithChildren
  '/conservation': typeof ConservationRoute
  '/guide': typeof GuideRoute
  '/kids': typeof KidsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/missions': typeof MissionsRouteWithChildren
  '/passport': typeof PassportRoute
  '/plan': typeof PlanRoute
  '/schedule': typeof ScheduleRoute
  '/animals/$slug': typeof AnimalsSlugRoute
  '/missions/$slug': typeof MissionsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRouteWithChildren
  '/conservation': typeof ConservationRoute
  '/guide': typeof GuideRoute
  '/kids': typeof KidsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/missions': typeof MissionsRouteWithChildren
  '/passport': typeof PassportRoute
  '/plan': typeof PlanRoute
  '/schedule': typeof ScheduleRoute
  '/animals/$slug': typeof AnimalsSlugRoute
  '/missions/$slug': typeof MissionsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animals'
    | '/conservation'
    | '/guide'
    | '/kids'
    | '/learn'
    | '/map'
    | '/missions'
    | '/passport'
    | '/plan'
    | '/schedule'
    | '/animals/$slug'
    | '/missions/$slug'
    | '/sitemap/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animals'
    | '/conservation'
    | '/guide'
    | '/kids'
    | '/learn'
    | '/map'
    | '/missions'
    | '/passport'
    | '/plan'
    | '/schedule'
    | '/animals/$slug'
    | '/missions/$slug'
    | '/sitemap/xml'
  id:
    | '__root__'
    | '/'
    | '/animals'
    | '/conservation'
    | '/guide'
    | '/kids'
    | '/learn'
    | '/map'
    | '/missions'
    | '/passport'
    | '/plan'
    | '/schedule'
    | '/animals/$slug'
    | '/missions/$slug'
    | '/sitemap/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimalsRoute: typeof AnimalsRouteWithChildren
  ConservationRoute: typeof ConservationRoute
  GuideRoute: typeof GuideRoute
  KidsRoute: typeof KidsRoute
  LearnRoute: typeof LearnRoute
  MapRoute: typeof MapRoute
  MissionsRoute: typeof MissionsRouteWithChildren
  PassportRoute: typeof PassportRoute
  PlanRoute: typeof PlanRoute
  ScheduleRoute: typeof ScheduleRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conservation': {
      id: '/conservation'
      path: '/conservation'
      fullPath: '/conservation'
      preLoaderRoute: typeof ConservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals': {
      id: '/animals'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AnimalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$slug': {
      id: '/missions/$slug'
      path: '/$slug'
      fullPath: '/missions/$slug'
      preLoaderRoute: typeof MissionsSlugRouteImport
      parentRoute: typeof MissionsRoute
    }
    '/animals/$slug': {
      id: '/animals/$slug'
      path: '/$slug'
      fullPath: '/animals/$slug'
      preLoaderRoute: typeof AnimalsSlugRouteImport
      parentRoute: typeof AnimalsRoute
    }
  }
}

interface AnimalsRouteChildren {
  AnimalsSlugRoute: typeof AnimalsSlugRoute
}

const AnimalsRouteChildren: AnimalsRouteChildren = {
  AnimalsSlugRoute: AnimalsSlugRoute,
}

const AnimalsRouteWithChildren =
  AnimalsRoute._addFileChildren(AnimalsRouteChildren)

interface MissionsRouteChildren {
  MissionsSlugRoute: typeof MissionsSlugRoute
}

const MissionsRouteChildren: MissionsRouteChildren = {
  MissionsSlugRoute: MissionsSlugRoute,
}

const MissionsRouteWithChildren = MissionsRoute._addFileChildren(
  MissionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimalsRoute: AnimalsRouteWithChildren,
  ConservationRoute: ConservationRoute,
  GuideRoute: GuideRoute,
  KidsRoute: KidsRoute,
  LearnRoute: LearnRoute,
  MapRoute: MapRoute,
  MissionsRoute: MissionsRouteWithChildren,
  PassportRoute: PassportRoute,
  PlanRoute: PlanRoute,
  ScheduleRoute: ScheduleRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
